### ISSUE TITLE
Fishing seemingly nonfunctional

### ISSUE THREAD

**Issue by AstridCone** [RingComics/yajan#23]
This might be a case of me being stupid, but: fishing doesn't seem to work, like outright. I wave my fishing rod at the water, it even consumes bait if I bring it. But even when it says I caught something, I receive nothing, not even experience in the skill. Parts of it definitely functions, I mean I'm getting the messages and it eats bait, it just seemingly ends there 🤷

I'm on the current release version, I don't really know what else useful there is to say

**Comment by RingComics** [comment]
This should be fixed now that Water Life has been removed.

**Comment by RingComics** [comment]
Confirmed fixed
