### ISSUE TITLE
Sitting NPC in Census office is misaligned

### ISSUE THREAD

**Issue by RingComics** [RingComics/yajan#25]
Source mod: Beautiful Cities of Morrowind (Animated Morrowind Patch)
Source file: `Animated Morrowind - Merged.esp`
Cell: "Seyda Neen, Census and Excise Office"
Issue: Dude is squatting inside the chair.

**Comment by Nwah-Extraordinaire** [comment]
I've found multiple NPCs with the same problem. Didn't encounter them in 6.2. I just started recording the names down in my notes, so I'll update from time to time with batches of names.

So far since recording:
-Caldera, Governor's Hall: Llius Laerzo, in table across from main entrance

**Comment by RingComics** [comment]
This is a bug that just happens sometimes with Animated Morrowind NPCs
